name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakatime.com/api # optional
          # content
          SECTION_TITLE: "Some unnecessary stats of me"
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: ░▒▓█ # optional
          IGNORED_LANGUAGES: YAML JSON TOML XML Binary # optional
          SHOW_OS: True
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
